steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/backend-reto-tecnico/api-go:$SHORT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/backend-reto-tecnico/api-go:latest'
      - './api-go'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/backend-reto-tecnico/api-go'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'api-go'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/backend-reto-tecnico/api-go:$SHORT_SHA'
      - '--region=us-central1'
      - '--platform=managed'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/backend-reto-tecnico/api-go:$SHORT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/backend-reto-tecnico/api-go:latest'

# Requerido al usar una cuenta de servicio personalizada
options:
  logging: CLOUD_LOGGING_ONLY
